// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: route/route_guide.proto
#ifndef GRPC_route_2froute_5fguide_2eproto__INCLUDED
#define GRPC_route_2froute_5fguide_2eproto__INCLUDED

#include "route_guide.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace route {

class RouteGuide final {
 public:
  static constexpr char const* service_full_name() {
    return "route.RouteGuide";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetPerson(::grpc::ClientContext* context, const ::route::IdInBook& request, ::tutorial::Person* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tutorial::Person>> AsyncGetPerson(::grpc::ClientContext* context, const ::route::IdInBook& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tutorial::Person>>(AsyncGetPersonRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tutorial::Person>> PrepareAsyncGetPerson(::grpc::ClientContext* context, const ::route::IdInBook& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::tutorial::Person>>(PrepareAsyncGetPersonRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetPerson(::grpc::ClientContext* context, const ::route::IdInBook* request, ::tutorial::Person* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetPerson(::grpc::ClientContext* context, const ::route::IdInBook* request, ::tutorial::Person* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tutorial::Person>* AsyncGetPersonRaw(::grpc::ClientContext* context, const ::route::IdInBook& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::tutorial::Person>* PrepareAsyncGetPersonRaw(::grpc::ClientContext* context, const ::route::IdInBook& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetPerson(::grpc::ClientContext* context, const ::route::IdInBook& request, ::tutorial::Person* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tutorial::Person>> AsyncGetPerson(::grpc::ClientContext* context, const ::route::IdInBook& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tutorial::Person>>(AsyncGetPersonRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tutorial::Person>> PrepareAsyncGetPerson(::grpc::ClientContext* context, const ::route::IdInBook& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::tutorial::Person>>(PrepareAsyncGetPersonRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetPerson(::grpc::ClientContext* context, const ::route::IdInBook* request, ::tutorial::Person* response, std::function<void(::grpc::Status)>) override;
      void GetPerson(::grpc::ClientContext* context, const ::route::IdInBook* request, ::tutorial::Person* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::tutorial::Person>* AsyncGetPersonRaw(::grpc::ClientContext* context, const ::route::IdInBook& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::tutorial::Person>* PrepareAsyncGetPersonRaw(::grpc::ClientContext* context, const ::route::IdInBook& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetPerson_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetPerson(::grpc::ServerContext* context, const ::route::IdInBook* request, ::tutorial::Person* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPerson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPerson() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetPerson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerson(::grpc::ServerContext* /*context*/, const ::route::IdInBook* /*request*/, ::tutorial::Person* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPerson(::grpc::ServerContext* context, ::route::IdInBook* request, ::grpc::ServerAsyncResponseWriter< ::tutorial::Person>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetPerson<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetPerson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetPerson() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::route::IdInBook, ::tutorial::Person>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::route::IdInBook* request, ::tutorial::Person* response) { return this->GetPerson(context, request, response); }));}
    void SetMessageAllocatorFor_GetPerson(
        ::grpc::MessageAllocator< ::route::IdInBook, ::tutorial::Person>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::route::IdInBook, ::tutorial::Person>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetPerson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerson(::grpc::ServerContext* /*context*/, const ::route::IdInBook* /*request*/, ::tutorial::Person* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPerson(
      ::grpc::CallbackServerContext* /*context*/, const ::route::IdInBook* /*request*/, ::tutorial::Person* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetPerson<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetPerson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPerson() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetPerson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerson(::grpc::ServerContext* /*context*/, const ::route::IdInBook* /*request*/, ::tutorial::Person* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPerson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPerson() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetPerson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerson(::grpc::ServerContext* /*context*/, const ::route::IdInBook* /*request*/, ::tutorial::Person* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPerson(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetPerson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetPerson() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPerson(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetPerson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPerson(::grpc::ServerContext* /*context*/, const ::route::IdInBook* /*request*/, ::tutorial::Person* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetPerson(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPerson : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPerson() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::route::IdInBook, ::tutorial::Person>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::route::IdInBook, ::tutorial::Person>* streamer) {
                       return this->StreamedGetPerson(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPerson() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPerson(::grpc::ServerContext* /*context*/, const ::route::IdInBook* /*request*/, ::tutorial::Person* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPerson(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::route::IdInBook,::tutorial::Person>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetPerson<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetPerson<Service > StreamedService;
};

}  // namespace route


#endif  // GRPC_route_2froute_5fguide_2eproto__INCLUDED
